dearhr/dearhr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('users/', include('users.urls')),
]

dearhr/landing/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.welcome, name = "index"),
]

dearhr/users/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name ='users'
urlpatterns = [
    path('home/', views.home, name="home"),
    path('profile', views.profile, name="user_profile"),
    path('confirm', views.confirm, name="user_confirm"),
    path('register/', views.reg, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='users/page_login.html'), name="user_login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="user_logout"),

    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='user_activate'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name="password_reset_complete"),

path('join/', views.join, name="join"),

    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complate.html'), name='password_reset_complete'),
]

dearhr/landing/models.py
from django.db import models

# Create your models here.

dearhr/users/models.py
from django.db import models

# Create your models here.

dearhr/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password1', 'password2'  ]

dearhr/landing/views.py
from django.shortcuts import render

def welcome(request):
    return render(request, 'landing/index.html')

dearhr/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from .forms import UserRegisterForm


from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.sites.models import Site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings

from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout


# this is the home page after the user is logged in
def home(request):
    return render(request, 'users/home.html')


# this is the confirmation page after the user has registered and is redirected here.
def confirm(request):
    return render(request, 'users/page_confirmation.html')

def join(request):
    return render(request, 'users/join.html')

def password_reset_confirm(request, uidb64, token):
    return render(request, 'users/password_reset_confirm.html')
# this is the registration page. the page that the user is making a user account
def reg(request):
    if request.method == 'POST':
        form= UserRegisterForm (request.POST)
        if form.is_valid():
            user = form.save(commit = False)
            user.is_active = False
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage( mail_subject, message, to=[to_email] )
            email.send()
            last_name = form.cleaned_data.get('last_name')
            messages.success(request, f'thanks {last_name}')
            form.save()
            return redirect('users:user_confirm')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        # login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!') 


@login_required
def profile(request):
    return render(request, 'users/page_profile.html')

# def logout_view(request):
#     logout(request)












# def sign(request):
#     if request.method == 'POST':
#         form= UserRegisterForm (request.POST)
#         if form.is_valid():
#             save_it = form.save(commit=False)
#             # save_it.save()
#             # send_mail(subject, message, from_email, to_list, fail_silently=True)
#             subject=" thank you for registering"
#             message = "welcome to the DearHR platform./nThis is the activation link"
#             from_email = settings.EMAIL_HOST_USER
#             to_list = [save_it.email]

#             # send_mail(subject, message, from_email , to_list)
#             last_name = form.cleaned_data.get('last_name')
#             messages.success(request, f'thanks {last_name} | {save_it.email}')
#             form.save()
#             return redirect('users:user_confirm')
#         else:
#             return redirect('users:register')
#     else:
#         form = UserRegisterForm()
#     return render(request, 'users/register.html', {'form': form})














    # if request.method == 'POST':
    #     first_name = request.POST.get('first_name')
    #     last_name = request.POST.get('last_name')        
    #     email = request.POST.get('email')
    #     password = request.POST.get('password')
    #     messages.success(request, f'{last_name}')



        # return HttpResponse('<p> done</p>')
        # return redirect ('register')
        # return render(request, 'users/page_confirmation.html')
    # else:
    #     messages.warning(request, f'Account was not created for {last_name}!')
    #     return render( request, 'users/page_confirmation.html')

dearhr/users/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

{% endautoescape %}

dearhr/users/templates/users/join.html
{% extends 'users/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
        <div class="page-wrapper auth">
            <div class="page-inner bg-brand-gradient">
                <div class="page-content-wrapper bg-transparent m-0">
                    <div class="height-10 w-100 shadow-lg px-4 bg-brand-gradient">
                        <div class="d-flex align-items-center container p-0">
                            <div class="page-logo width-mobile-auto m-0 align-items-center justify-content-center p-0 bg-transparent bg-img-none shadow-0 height-9 border-0">
                                <a href="javascript:void(0)" class="page-logo-link press-scale-down d-flex align-items-center">
                                    <img src="{% static 'users/img/logo.png' %}" alt="SmartAdmin WebApp" aria-roledescription="logo">
                                    <span class="page-logo-text mr-1">DearHR</span>
                                </a>
                            </div> 
                            <a href="{% url 'users:user_login' %}" class="btn-link text-white ml-auto">
                               <strong>Login Here</strong>
                            </a>
                        </div>
                    </div>
                    <div class="flex-1" style="background: url({% static 'users/img/svg/pattern-1.svg' %}) no-repeat center bottom fixed; background-size: cover;">
                        <div class="container py-4 py-lg-5 my-lg-5 px-4 px-sm-0">
                            <div class="row">
                                <div class="col col-md-5 col-lg-5 hidden-sm-down">
                                    <h2 class="fs-xxl fw-500 mt-4 text-white">
                                        Join us today ..
                                        <small class="h3 fw-300 mt-3 mb-5 text-white opacity-60">
                                            here is the place for a short about section.

                                        </small>
                                    </h2>
                                    <a href="#" class="fs-lg fw-500 text-white opacity-70">Learn more &gt;&gt;</a>
                                    <div class="d-sm-flex flex-column align-items-center justify-content-center d-md-block">
                                        <div class="px-0 py-1 mt-5 text-white fs-nano opacity-50">
                                            Find us on social media
                                        </div>
                                        <div class="d-flex flex-row opacity-70">
                                            <a href="#" class="mr-2 fs-xxl text-white">
                                                <i class="fab fa-facebook-square"></i>
                                            </a>
                                            <a href="#" class="mr-2 fs-xxl text-white">
                                                <i class="fab fa-twitter-square"></i>
                                            </a>
                                            <a href="#" class="mr-2 fs-xxl text-white">
                                                <i class="fab fa-google-plus-square"></i>
                                            </a>
                                            <a href="#" class="mr-2 fs-xxl text-white">
                                                <i class="fab fa-linkedin"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>

                             
                                <div class="col-sm-12 col-md-5 col-lg-4  ml-auto">
                                    <!-- <div class="card p-4 rounded-plus bg-faded align-items-center"> -->

                                        <div class=" my-2">
                                            <a href="{% url 'users:register' %}">
                                                <button id="js-login-btn" type="submit" class="btn btn-primary btn-block btn-lg"> <strong>I am a job Seeker</strong> </button>
                                            </a>                                        </div>
                                        <br>
                                        <br>
                                        <div class=" my-2">
                                            <a href="{% url 'users:register' %}">
                                                <button id="js-login-btn" type="submit" class="btn btn-primary btn-block btn-lg"> <strong>I am an HR Manager</strong> </button>
                                            </a>                                        </div>
                                        <br><br>
                                        <div class=" my-2">
                                            <a href="{% url 'users:register' %}">
                                                <button id="js-login-btn" type="submit" class="btn btn-primary btn-block btn-lg"> <strong>I am a Serivce Provider</strong> </button>
                                            </a>
                                        </div>
                                        <br><br>
                                    <!-- </div> -->
                                </div>
                            </div>
                            <div class="position-absolute pos-bottom pos-left pos-right p-3 text-center text-white">
                                2020 © DearHR&nbsp;<a href='https://www.dearhr.com' class='text-white opacity-40 fw-500' title='dearhr.com' target='_blank'>dearhr.com</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endblock content %}

dearhr/users/templates/users/page_confirmation.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}
        <div class="page-wrapper auth">
            <div class="page-inner bg-brand-gradient">
                <div class="page-content-wrapper bg-transparent m-0">
                    <div class="height-10 w-100 shadow-lg px-4 bg-brand-gradient">
                        <div class="d-flex align-items-center container p-0">
                            <div class="page-logo width-mobile-auto m-0 align-items-center justify-content-center p-0 bg-transparent bg-img-none shadow-0 height-9 border-0">
                                <a href="javascript:void(0)" class="page-logo-link press-scale-down d-flex align-items-center">
                                    <img src="{% static 'users/img/logo.png'%}" alt="SmartAdmin WebApp" aria-roledescription="logo">
                                    <span class="page-logo-text mr-1"> DearHR</span>
                                </a>
                            </div>
                            <span class="text-white opacity-50 ml-auto mr-2 hidden-sm-down">
                                Already a member?
                            </span>
                            <a href="{% url 'users:user_login' %}" class="btn-link text-white ml-auto ml-sm-0">
                                 Login here
                            </a>
                        </div>
                    </div>
                    {% endblock content %}
                    
                    {% block content2 %}
                    <div class="flex-1" style="background: url({% static 'users/img/svg/pattern-1.svg' %}) no-repeat center bottom fixed; background-size: cover;">
                        <div class="container py-4 py-lg-5 my-lg-5 px-4 px-sm-0">
                            <div class="row">
                                {% if messages %}
                                    {% for message in messages %}
                                <div class="col-xl-12">
                                    <h2 class="fs-xxl fw-500 mt-4 text-white text-center">
                                        Thank you {{message}} for registrering! Please check your email.
                                        <small class="h3 fw-300 mt-3 mb-5 text-white opacity-70 hidden-sm-down">
                                            We’ve sent a message to <strong>drlantern@gotbootstrap.com</strong> with a link to activate your account.
                                        </small>
                                    </h2>
                                </div>
                                   {% endfor %}
                                {% endif %}
                                <div class="col-xl-6 ml-auto mr-auto">
                                    <div class="card p-4 rounded-plus bg-faded">
                                        <!-- <div class="alert alert-primary text-dark" role="alert">
                                            <strong>Heads Up!</strong> Due to server maintenance from 9:30GTA to 12GTA, the verification emails could be delayed by up to 10 minutes.
                                        </div> -->
                                        <a href="javascript:void(0);" class="h4">
                                            <i class="fal fa-chevron-right mr-2"></i> Didn’t get an email?
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="position-absolute pos-bottom pos-left pos-right p-3 text-center text-white">
                            2020 © DearHR &nbsp;<a href='https://www.dearhr.com' class='text-white opacity-40 fw-500' title='dearhr.com' target='_blank'>dearhr.com</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endblock content2 %}

dearhr/users/templates/users/page_register.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}

<div class="page-wrapper auth">
    <div class="page-inner bg-brand-gradient">
        <div class="page-content-wrapper bg-transparent m-0">
            <div class="height-10 w-100 shadow-lg px-4 bg-brand-gradient">
                <div class="d-flex align-items-center container p-0">
                    <div class="page-logo width-mobile-auto m-0 align-items-center justify-content-center p-0 bg-transparent bg-img-none shadow-0 height-9 border-0">
                        <a href="javascript:void(0)" class="page-logo-link press-scale-down d-flex align-items-center">
                            <img src="{% static 'user/img/logo.png' %}" alt="DearHR " aria-roledescription="logo">
                            <span class="page-logo-text mr-1">DearHR</span>
                        </a>
                    </div>
                    <span class="text-white opacity-50 ml-auto mr-2 hidden-sm-down">
                        Already a member?
                    </span>
                    <a href="{% url 'users:user_login' %}" class="btn-link text-white ml-auto ml-sm-0">
                         Login here
                    </a>
                </div>
            </div>
            <div class="flex-1" style="background: url({% static 'users/img/svg/pattern-1.svg' %}) no-repeat center bottom fixed; background-size: cover;">
                <div class="container py-4 py-lg-5 my-lg-5 px-4 px-sm-0">
                    <div class="row">
                        <div class="col-xl-12">
                            <h2 class="fs-xxl fw-500 mt-4 text-white text-center">
                                Register now, its free!
                                <small class="h3 fw-300 mt-3 mb-5 text-white opacity-60 hidden-sm-down">
                                    Your registration is free for a life time. Enjoy DearHR for alawys. 
                                    <br>We want you to succeed!
                                </small>
                            </h2>
                        </div>
                        
                        <div class="col-xl-6 ml-auto mr-auto">
                            <div class="card p-4 rounded-plus bg-faded">
                                <!-- <div class="alert alert-primary text-dark" role="alert">
                                    <strong>Heads Up!</strong> Due to server maintenance from 9:30GTA to 12GTA, the verification emails could be delayed by up to 10 minutes.
                                </div> -->
                                <form id="js-login" novalidate="" method="POST" action="{% url 'users:registering' %}"> 
                                    {% csrf_token %}
                                    <div class="form-group row">
                                        <label class="col-xl-12 form-label" for="fname">Your first and last name</label>
                                        <div class="col-6 pr-1">
                                            <input type="text" id="fname" name="first_name" class="form-control" placeholder="First Name" required>
                                            <div class="invalid-feedback">No, you missed this one.</div>
                                        </div>
                                        <div class="col-6 pl-1">
                                            <input type="text" id="lname" name="last_name" class="form-control" placeholder="Last Name" required>
                                            <div class="invalid-feedback">No, you missed this one.</div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label" for="emailverify">Email will be needed for verification and account recovery</label>
                                        <input type="email" id="emailverify" name="email" class="form-control" placeholder="Email for verification" required>
                                        <div class="invalid-feedback">No, you missed this one.</div>
                                        <div class="help-block">Your email will also be your username</div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label" for="userpassword">Pick a password: <br>Don't reuse your bank password, we didn't spend a lot on security for this app.</label>
                                        <input type="password" id="userpassword" name="password" class="form-control" placeholder="minimm 8 characters" required>
                                        <div class="invalid-feedback">Sorry, you missed this one.</div>
                                        <div class="help-block">Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.</div>
                                    </div>
                                    <div class="form-group demo">
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="terms" required>
                                            <label class="custom-control-label" for="terms"> I agree to terms & conditions</label>
                                            <div class="invalid-feedback">You must agree before proceeding</div>
                                        </div>
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="newsletter">
                                            <label class="custom-control-label" for="newsletter">Sign up for newsletters (dont worry, we won't send so many)</label>
                                        </div>
                                    </div>
                                    <div class="row no-gutters">
                                        <div class="col-md-4 ml-auto text-right">
                                            <button id="js-login-btn" type="submit" class="btn btn-block btn-danger btn-lg mt-3">Send verification</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="position-absolute pos-bottom pos-left pos-right p-3 text-center text-white">
                    2020 © DearHR &nbsp;<a href='https://www.dearhr.com' class='text-white opacity-40 fw-500' title='gotbootstrap.com' target='_blank'>dearhr.com</a>
                </div>
            </div>
        </div>
    </div>
</div>

        {% endblock content %}

dearhr/users/templates/users/password_reset.html
{% extends 'users/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

        <div class="page-wrapper auth">
            <div class="page-inner bg-brand-gradient">
                <div class="page-content-wrapper bg-transparent m-0">
                    <div class="height-10 w-100 shadow-lg px-4 bg-brand-gradient">
                        <div class="d-flex align-items-center container p-0">
                            <div class="page-logo width-mobile-auto m-0 align-items-center justify-content-center p-0 bg-transparent bg-img-none shadow-0 height-9 border-0">
                                <a href="javascript:void(0)" class="page-logo-link press-scale-down d-flex align-items-center">
                                    <img src="{% static 'users/img/logo.png' %}" alt="DearHR" aria-roledescription="logo">
                                    <span class="page-logo-text mr-1"> DearHR</span>
                                </a>
                            </div>
                            <span class="text-white opacity-50 ml-auto mr-2 hidden-sm-down">
                                remembered your password?
                            </span>
                            <a href="{% url 'users:user_login' %}" class="btn-link text-white ml-auto ml-sm-0">
                                 Login here
                            </a>
                        </div>
                    </div>
                    <div class="flex-1" style="background: url(img/svg/pattern-1.svg) no-repeat center bottom fixed; background-size: cover;">
                        <div class="container py-4 py-lg-5 my-lg-5 px-4 px-sm-0">
                            <div class="row">
                                <div class="col-xl-12">
                                    <h2 class="fs-xxl fw-500 mt-4 text-white text-center">
                                        "My dog ate my password"
                                        <small class="h3 fw-300 mt-3 mb-5 text-white opacity-60 hidden-sm-down">
                                            Not a problem, happens to the best of us. Just use the form below to reset it!
                                        </small>
                                    </h2>
                                </div>
                                <div class="col-xl-6 ml-auto mr-auto">
                                    <div class="card p-4 rounded-plus bg-faded">
                                       
                                        <form id="js-login" novalidate="" method="POST">
                                            {% csrf_token %}
                                            {{form | crispy}}

                                            <div class="row no-gutters">
                                                <div class="col-md-4 ml-auto text-right">
                                                    <button id="js-login-btn" type="submit" class="btn btn-primary">Reset Password</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="d-block text-center text-white">
                            2020 © DearHR &nbsp;<a href='https://www.dearhr.com' class='text-white opacity-40 fw-500' title='gotbootstrap.com' target='_blank'>dearhr.com</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock content %}

dearhr/users/templates/users/password_reset_done.html
{% extends 'users/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
        <div class="page-wrapper auth">
            <div class="page-inner bg-brand-gradient">
                <div class="page-content-wrapper bg-transparent m-0">
                    <div class="height-10 w-100 shadow-lg px-4 bg-brand-gradient">
                        <div class="d-flex align-items-center container p-0">
                            <div class="page-logo width-mobile-auto m-0 align-items-center justify-content-center p-0 bg-transparent bg-img-none shadow-0 height-9 border-0">
                                <a href="javascript:void(0)" class="page-logo-link press-scale-down d-flex align-items-center">
                                    <img src="{% static 'users/img/logo.png' %}" alt="SmartAdmin WebApp" aria-roledescription="logo">
                                    <span class="page-logo-text mr-1">DearHR</span>
                                </a>
                            </div>
                            <a href="{% url 'users:users_login' %}" class="btn-link text-white ml-auto">
                                login here
                            </a>
                        </div>
                    </div>
                    <div class="flex-1" style="background: url({% static 'users/img/svg/pattern-1.svg' %}) no-repeat center bottom fixed; background-size: cover;">
                        <div class="container py-4 py-lg-5 my-lg-5 px-4 px-sm-0">
                            <div class="row">
                                <div class="alert alert-info" >
                                    an email has been sent with instructions to reset your password
                                </div>
                            </div>
                            <div class="position-absolute pos-bottom pos-left pos-right p-3 text-center text-white">
                                2020 © DearHR&nbsp;<a href='https://www.dearhr.com' class='text-white opacity-40 fw-500' title='dearhr.com' target='_blank'>dearhr.com</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endblock content %}

dearhr/users/templates/users/site.html
{% block content %}

{% if messages %}
    {% for message in messages %}
<div class="col-xl-12">
    <h2 class="fs-xxl fw-500 mt-4 text-white text-center">
        Thank you {{message}} for registrering! Please check your email.
        
    </h2>
</div>
    {% endfor %}
{% endif %}

{% for a in data %}
{{a}}
{% endfor  %}

{% endblock content %}

dearhr/users/templates/users/template.html
{% load static %}